### ISSUE TITLE
Timeseries Mapping improvements

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/AirFireResearchGUIs#1]
Two-step selection of date ranges is awkward because it forces an update whenever wither is selected.

Let's both simplify things and make them more targeted to AirFire with the following changes:

- [x] Only have a single selector (calendar or a YYYYMM in a selector) to choose the month
- [x] Use `monitor_loadMonth()` which won't ever generate the following error: "Requests joining anuual files with 'daily' or 'latest' files can be time consuming. Please supply monitorIDs to subset the data"
- [x] Color the monitors using `PWFSLSmoke::AQI$colors` and `$breaks`

**Comment by hansmrtn** [comment]
`monitor_loadMonth()` is not a function? implemented anyways! See `example_timeseriesMap_2.Rmd`
