### ISSUE TITLE
AirFireModeling Example 1

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/AirFireResearchGUIs#3]
I love the interactivity of this one. A person doesn't need to know _anything_ about the **AirFireModeling** package. They just have to run the markdown document.

I think this UI is a good start and would like to begin with the following simplifications:

- [x] Remove the lon/lat input and simply hardcode a list of model names.
- [x] Orient the remaining GUI elements -- `modelName`, `modelRunDate`, load, `modelHour` -- horizontally to give more room to the graphic

**Future Direction**

If we decide to pursue this, we should really have a design session where we make lots of drawings and talk about pros and cons of different features. The following is where my mind goes right now.

* An ideal UI would have the model timestep raster overlaid on a leaflet map so a user can see where the smoke is.
* Clicking on the map would select a location. (a pin could mark the location and be moved around)

Below a horizontal bar

* Horizontally arranged selectors would allow selection of additional parameters like `count`
* Location selection (with leaflet or other element) would trigger generation of a `raster_spaghettiPlot()`.

**Comment by hansmrtn** [comment]
Agreed! That sounds like a good UI. Issue resolution shown in `example_airefiremodeling_2.Rmd`
